### PR TITLE
VIG-1994: LORA azure custom module

### PR DESCRIPTION
**Pull request by writankarmatellio**

### CODE REVIEW

**Comment by mveea** [comment]
Hi @writankarmatellio 
Thanks for the PR. One thing bothers me: you use vbus-cmd to discover the mqtt url and after run some py code.
A cleaner way would be to use vbus python library. Would it take you long to do that change?

**Comment by writankarmatellio** [comment]
Hi @mveea,
We have used vbus-cmd in order to reduce the size of the image.
Now the size of the image is 167MB.
If we use the vbus-bus python client we need to install certain dependencies like the _pyGobject, pyCairo_  in the 2nd Stage etc. which would increase the size of the image.

Are code changes required for this minor requirement?

**Comment by mveea** [comment]
ok I understand. Not great but let's keep it that way for now.
When we'll move to edgeX there won't be a python library anymore anyway....

**Comment by writankarmatellio** [comment]
Thanks
Please approve and merge the PR.

**Pull request merged**
